name: rick_and_morty_app
description: Rick and Morty's characters finder

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  connectivity: ^3.0.6
  dartz: ^0.10.0-nullsafety.2
  dio: ^4.0.0
  mobx: ^2.0.0
  flutter_mobx: ^2.0.0
  flutter_hooks: ^0.18.0
  freezed: ^0.14.0
  get_it: ^6.0.0
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  json_serializable: ^4.1.3
  logger: ^1.0.0
  sizer: ^2.0.13
  provider: ^5.0.0
  mockito: ^5.0.0
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.12.2
  mobx_codegen: ^2.0.0
  hive_generator: ^1.1.0

flutter:
  uses-material-design: true

fonts:
  - family: Lato
    fonts:
      - asset: assets/fonts/Lato-Regular.ttf
      - asset: assets/fonts/Lato-Bold.ttf
        weight: 700
  - family: Anton
    fonts:
      - asset: assets/fonts/Anton-Regular.ttf
